"""Initial schema

Revision ID: c5dbe886de7d
Revises: 
Create Date: 2025-11-30 11:09:39.535115

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5dbe886de7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('impersonator_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('changes_summary', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('retention_required', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_sensitive'), 'audit_logs', ['is_sensitive'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_email'), 'audit_logs', ['user_email'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_vendor_id'), 'audit_logs', ['vendor_id'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_timestamp_sensitive', 'audit_logs', ['timestamp', 'is_sensitive'], unique=False)
    op.create_index('ix_audit_user_timestamp', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_vendor_action_timestamp', 'audit_logs', ['vendor_id', 'action', 'timestamp'], unique=False)
    op.create_table('data_access_logs',
    sa.Column('accessor_id', sa.String(length=36), nullable=False),
    sa.Column('accessor_email', sa.String(length=255), nullable=False),
    sa.Column('accessor_role', sa.String(length=50), nullable=False),
    sa.Column('data_subject_id', sa.String(length=36), nullable=False),
    sa.Column('data_subject_email', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('access_method', sa.String(length=20), nullable=False),
    sa.Column('records_accessed', sa.Integer(), nullable=False),
    sa.Column('access_purpose', sa.String(length=200), nullable=False),
    sa.Column('legal_basis', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_access_accessor_time', 'data_access_logs', ['accessor_id', 'accessed_at'], unique=False)
    op.create_index(op.f('ix_data_access_logs_accessed_at'), 'data_access_logs', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_data_access_logs_accessor_id'), 'data_access_logs', ['accessor_id'], unique=False)
    op.create_index(op.f('ix_data_access_logs_correlation_id'), 'data_access_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_data_access_logs_data_subject_id'), 'data_access_logs', ['data_subject_id'], unique=False)
    op.create_index(op.f('ix_data_access_logs_data_type'), 'data_access_logs', ['data_type'], unique=False)
    op.create_index(op.f('ix_data_access_logs_vendor_id'), 'data_access_logs', ['vendor_id'], unique=False)
    op.create_index('ix_data_access_subject_time', 'data_access_logs', ['data_subject_id', 'accessed_at'], unique=False)
    op.create_index('ix_data_access_vendor_type', 'data_access_logs', ['vendor_id', 'data_type'], unique=False)
    op.create_table('data_deletion_logs',
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('deletion_reason', sa.String(length=100), nullable=False),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('user_request_id', sa.String(length=36), nullable=True),
    sa.Column('record_summary', sa.JSON(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anonymized', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_deletion_logs_data_type'), 'data_deletion_logs', ['data_type'], unique=False)
    op.create_index(op.f('ix_data_deletion_logs_deleted_at'), 'data_deletion_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_data_deletion_logs_vendor_id'), 'data_deletion_logs', ['vendor_id'], unique=False)
    op.create_index('ix_deletion_reason', 'data_deletion_logs', ['deletion_reason'], unique=False)
    op.create_index('ix_deletion_vendor_type_date', 'data_deletion_logs', ['vendor_id', 'data_type', 'deleted_at'], unique=False)
    op.create_table('data_retention_policies',
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('legal_basis', sa.String(length=100), nullable=False),
    sa.Column('auto_delete_enabled', sa.Boolean(), nullable=False),
    sa.Column('anonymize_instead', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_policies_data_type'), 'data_retention_policies', ['data_type'], unique=False)
    op.create_index(op.f('ix_data_retention_policies_is_active'), 'data_retention_policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_data_retention_policies_vendor_id'), 'data_retention_policies', ['vendor_id'], unique=False)
    op.create_index('ix_retention_vendor_type', 'data_retention_policies', ['vendor_id', 'data_type'], unique=False)
    op.create_table('data_subject_requests',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specific_data', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.String(length=36), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('export_file_url', sa.String(length=500), nullable=True),
    sa.Column('deletion_confirmed', sa.Boolean(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_subject_requests_deadline'), 'data_subject_requests', ['deadline'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_request_type'), 'data_subject_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_requested_at'), 'data_subject_requests', ['requested_at'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_status'), 'data_subject_requests', ['status'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_user_email'), 'data_subject_requests', ['user_email'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_user_id'), 'data_subject_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_vendor_id'), 'data_subject_requests', ['vendor_id'], unique=False)
    op.create_index('ix_dsar_deadline', 'data_subject_requests', ['deadline'], unique=False)
    op.create_index('ix_dsar_user_type', 'data_subject_requests', ['user_id', 'request_type'], unique=False)
    op.create_index('ix_dsar_vendor_status', 'data_subject_requests', ['vendor_id', 'status'], unique=False)
    op.create_table('event_data',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Event name'),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False, comment='Date/time of event'),
    sa.Column('location', sa.String(length=500), nullable=True, comment='Event location/venue'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='Event latitude'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='Event longitude'),
    sa.Column('expected_attendance', sa.Integer(), nullable=False, comment='Expected number of attendees'),
    sa.Column('is_special', sa.Boolean(), nullable=False, comment='Whether this is a special/major event'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Source of event data (manual, eventbrite, hardcoded)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Event description'),
    sa.Column('eventbrite_id', sa.String(length=255), nullable=True, comment='Eventbrite event ID (if from API)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_data_date_range', 'event_data', ['event_date'], unique=False)
    op.create_index(op.f('ix_event_data_event_date'), 'event_data', ['event_date'], unique=False)
    op.create_index(op.f('ix_event_data_eventbrite_id'), 'event_data', ['eventbrite_id'], unique=False)
    op.create_index('ix_event_data_location', 'event_data', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_event_data_vendor_date', 'event_data', ['vendor_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_event_data_vendor_id'), 'event_data', ['vendor_id'], unique=False)
    op.create_table('legal_holds',
    sa.Column('hold_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('data_types', sa.JSON(), nullable=False),
    sa.Column('user_ids', sa.JSON(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('released_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_hold_vendor_active', 'legal_holds', ['vendor_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_legal_holds_hold_name'), 'legal_holds', ['hold_name'], unique=False)
    op.create_index(op.f('ix_legal_holds_is_active'), 'legal_holds', ['is_active'], unique=False)
    op.create_index(op.f('ix_legal_holds_vendor_id'), 'legal_holds', ['vendor_id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('stripe_payment_method_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('card_brand', sa.String(length=50), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_exp_month', sa.Integer(), nullable=True),
    sa.Column('card_exp_year', sa.Integer(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_last4', sa.String(length=4), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_stripe_customer_id'), 'payment_methods', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_stripe_payment_method_id'), 'payment_methods', ['stripe_payment_method_id'], unique=True)
    op.create_index('ix_payment_methods_vendor_default', 'payment_methods', ['vendor_id', 'is_default'], unique=False)
    op.create_index(op.f('ix_payment_methods_vendor_id'), 'payment_methods', ['vendor_id'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Product name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Product description'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Price per unit in USD'),
    sa.Column('square_item_id', sa.String(length=255), nullable=True, comment='Square catalog item ID'),
    sa.Column('square_variation_id', sa.String(length=255), nullable=True, comment='Square item variation ID'),
    sa.Column('square_synced_at', sa.DateTime(timezone=True), nullable=True, comment='Last sync from Square'),
    sa.Column('category', sa.String(length=100), nullable=True, comment="Product category (e.g., 'Vegetables', 'Fruits')"),
    sa.Column('tags', sa.Text(), nullable=True, comment='Comma-separated tags for search'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether product is currently available'),
    sa.Column('is_seasonal', sa.Boolean(), nullable=False, comment='Whether product is seasonal'),
    sa.Column('season_start_month', sa.Integer(), nullable=True, comment='Season start month (1-12)'),
    sa.Column('season_end_month', sa.Integer(), nullable=True, comment='Season end month (1-12)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index('ix_products_square_item', 'products', ['vendor_id', 'square_item_id'], unique=False)
    op.create_index(op.f('ix_products_square_item_id'), 'products', ['square_item_id'], unique=False)
    op.create_index(op.f('ix_products_square_variation_id'), 'products', ['square_variation_id'], unique=False)
    op.create_index('ix_products_vendor_active', 'products', ['vendor_id', 'is_active'], unique=False)
    op.create_index('ix_products_vendor_category', 'products', ['vendor_id', 'category'], unique=False)
    op.create_index(op.f('ix_products_vendor_id'), 'products', ['vendor_id'], unique=False)
    op.create_table('sales',
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=False, comment='When sale occurred (UTC)'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total sale amount in USD'),
    sa.Column('square_order_id', sa.String(length=255), nullable=True, comment='Square order ID'),
    sa.Column('square_payment_id', sa.String(length=255), nullable=True, comment='Square payment ID'),
    sa.Column('square_location_id', sa.String(length=255), nullable=True, comment='Square location ID'),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Sale line items as JSON array'),
    sa.Column('weather_temp_f', sa.Numeric(precision=5, scale=2), nullable=True, comment='Temperature in Fahrenheit'),
    sa.Column('weather_condition', sa.String(length=50), nullable=True, comment="Weather condition (e.g., 'sunny', 'rainy')"),
    sa.Column('event_name', sa.String(length=255), nullable=True, comment='Associated market/event name'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_date_range', 'sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_square_location_id'), 'sales', ['square_location_id'], unique=False)
    op.create_index(op.f('ix_sales_square_order_id'), 'sales', ['square_order_id'], unique=True)
    op.create_index(op.f('ix_sales_square_payment_id'), 'sales', ['square_payment_id'], unique=False)
    op.create_index('ix_sales_vendor_date', 'sales', ['vendor_id', 'sale_date'], unique=False)
    op.create_index(op.f('ix_sales_vendor_id'), 'sales', ['vendor_id'], unique=False)
    op.create_index('ix_sales_vendor_square_order', 'sales', ['vendor_id', 'square_order_id'], unique=False)
    op.create_table('square_tokens',
    sa.Column('access_token_encrypted', sa.Text(), nullable=False, comment='Encrypted Square access token'),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False, comment='Encrypted Square refresh token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When access token expires (UTC)'),
    sa.Column('merchant_id', sa.String(length=255), nullable=False, comment='Square merchant ID'),
    sa.Column('scopes', sa.Text(), nullable=False, comment='Space-separated OAuth scopes'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether token is currently active'),
    sa.Column('last_refresh_at', sa.DateTime(timezone=True), nullable=True, comment='Last time token was refreshed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_square_tokens_merchant_id'), 'square_tokens', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_square_tokens_vendor_id'), 'square_tokens', ['vendor_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recommendations_limit', sa.Integer(), nullable=True),
    sa.Column('products_limit', sa.Integer(), nullable=True),
    sa.Column('venues_limit', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_period_end', 'subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_tier'), 'subscriptions', ['tier'], unique=False)
    op.create_index(op.f('ix_subscriptions_vendor_id'), 'subscriptions', ['vendor_id'], unique=False)
    op.create_index('ix_subscriptions_vendor_status', 'subscriptions', ['vendor_id', 'status'], unique=False)
    op.create_index('ix_subscriptions_vendor_tier', 'subscriptions', ['vendor_id', 'tier'], unique=False)
    op.create_table('user_consents',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_user_type', 'user_consents', ['user_id', 'consent_type'], unique=False)
    op.create_index('ix_consent_vendor_given', 'user_consents', ['vendor_id', 'consent_given'], unique=False)
    op.create_index(op.f('ix_user_consents_consent_given'), 'user_consents', ['consent_given'], unique=False)
    op.create_index(op.f('ix_user_consents_consent_type'), 'user_consents', ['consent_type'], unique=False)
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_consents_vendor_id'), 'user_consents', ['vendor_id'], unique=False)
    op.create_table('vendors',
    sa.Column('email', sa.String(length=255), nullable=False, comment="Vendor's login email (unique)"),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('business_name', sa.String(length=255), nullable=False, comment='Public-facing business name'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Contact phone number'),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False, comment="Pricing tier: 'mvp' ($29/month) or 'multi_location' ($79/month)"),
    sa.Column('subscription_status', sa.String(length=20), nullable=False, comment="Billing status: 'trial', 'active', 'suspended', 'cancelled'"),
    sa.Column('square_connected', sa.Boolean(), nullable=False, comment='Quick check if Square OAuth completed'),
    sa.Column('square_merchant_id', sa.String(length=255), nullable=True, comment='Square merchant ID for reference'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint("subscription_status IN ('trial', 'active', 'suspended', 'cancelled')", name='check_subscription_status'),
    sa.CheckConstraint("subscription_tier IN ('mvp', 'multi_location')", name='check_subscription_tier'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_email'), 'vendors', ['email'], unique=True)
    op.create_index(op.f('ix_vendors_square_merchant_id'), 'vendors', ['square_merchant_id'], unique=False)
    op.create_table('venues',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Market or venue name'),
    sa.Column('location', sa.String(length=500), nullable=False, comment='Address or location description'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='Latitude coordinate'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='Longitude coordinate'),
    sa.Column('typical_attendance', sa.Integer(), nullable=True, comment='Typical number of customers'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Vendor notes about this venue'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether vendor still attends this venue'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_venues_location_coords', 'venues', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_venues_name', 'venues', ['name'], unique=False)
    op.create_index('ix_venues_vendor_active', 'venues', ['vendor_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_venues_vendor_id'), 'venues', ['vendor_id'], unique=False)
    op.create_table('invoices',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invoice_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('hosted_invoice_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_due_date', 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_paid'), 'invoices', ['paid'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_stripe_invoice_id'), 'invoices', ['stripe_invoice_id'], unique=True)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.create_index('ix_invoices_vendor_date', 'invoices', ['vendor_id', 'invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False)
    op.create_index('ix_invoices_vendor_status', 'invoices', ['vendor_id', 'status'], unique=False)
    op.create_table('recommendations',
    sa.Column('market_date', sa.DateTime(timezone=True), nullable=False, comment='Date of farmers market'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Product to bring'),
    sa.Column('venue_id', sa.UUID(), nullable=True, comment='Venue/market location (optional)'),
    sa.Column('recommended_quantity', sa.Integer(), nullable=False, comment='Recommended quantity to bring'),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='Model confidence (0.0 to 1.0)'),
    sa.Column('predicted_sales', sa.Integer(), nullable=True, comment='Predicted units to sell'),
    sa.Column('predicted_revenue', sa.Numeric(precision=10, scale=2), nullable=True, comment='Predicted revenue in USD'),
    sa.Column('weather_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Weather forecast data used'),
    sa.Column('event_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Event data used'),
    sa.Column('historical_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Historical patterns used'),
    sa.Column('model_version', sa.String(length=50), nullable=False, comment='ML model version used'),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default='NOW()', nullable=False, comment='When recommendation was generated'),
    sa.Column('user_accepted', sa.Boolean(), nullable=True, comment='Whether vendor accepted recommendation'),
    sa.Column('actual_quantity_brought', sa.Integer(), nullable=True, comment='Actual quantity vendor brought'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_market_date'), 'recommendations', ['market_date'], unique=False)
    op.create_index('ix_recommendations_product_date', 'recommendations', ['product_id', 'market_date'], unique=False)
    op.create_index('ix_recommendations_vendor_generated', 'recommendations', ['vendor_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_recommendations_vendor_id'), 'recommendations', ['vendor_id'], unique=False)
    op.create_index('ix_recommendations_vendor_market_date', 'recommendations', ['vendor_id', 'market_date'], unique=False)
    op.create_index('ix_recommendations_venue_date', 'recommendations', ['venue_id', 'market_date'], unique=False)
    op.create_index(op.f('ix_recommendations_venue_id'), 'recommendations', ['venue_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('usage_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stripe_usage_record_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_subscription_id'), 'usage_records', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_usage_records_timestamp'), 'usage_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_usage_records_usage_type'), 'usage_records', ['usage_type'], unique=False)
    op.create_index(op.f('ix_usage_records_vendor_id'), 'usage_records', ['vendor_id'], unique=False)
    op.create_index('ix_usage_subscription_timestamp', 'usage_records', ['subscription_id', 'timestamp'], unique=False)
    op.create_index('ix_usage_vendor_type_period', 'usage_records', ['vendor_id', 'usage_type', 'billing_period_start'], unique=False)
    op.create_table('recommendation_feedback',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('actual_quantity_brought', sa.Integer(), nullable=True, comment='Actual quantity vendor brought to market'),
    sa.Column('actual_quantity_sold', sa.Integer(), nullable=True, comment='Actual quantity sold at market'),
    sa.Column('actual_revenue', sa.Numeric(precision=10, scale=2), nullable=True, comment='Actual revenue from sales'),
    sa.Column('quantity_variance', sa.Numeric(precision=10, scale=2), nullable=True, comment='Variance between recommended and actual sold (actual - recommended)'),
    sa.Column('variance_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Variance as percentage'),
    sa.Column('rating', sa.Integer(), nullable=True, comment='Vendor rating of recommendation accuracy (1-5)'),
    sa.Column('comments', sa.Text(), nullable=True, comment='Vendor feedback comments'),
    sa.Column('was_accurate', sa.Boolean(), nullable=True, comment='Whether recommendation was within acceptable range (±20%)'),
    sa.Column('was_overstocked', sa.Boolean(), nullable=True, comment='Whether vendor brought too much inventory'),
    sa.Column('was_understocked', sa.Boolean(), nullable=True, comment='Whether vendor ran out of stock'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False, comment='When feedback was submitted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('vendor_id', sa.UUID(), nullable=False, comment='Tenant isolation: references vendors.id'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_accuracy', 'recommendation_feedback', ['was_accurate'], unique=False)
    op.create_index('idx_feedback_rating', 'recommendation_feedback', ['rating'], unique=False)
    op.create_index('idx_feedback_vendor_submitted', 'recommendation_feedback', ['vendor_id', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_recommendation_id'), 'recommendation_feedback', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_vendor_id'), 'recommendation_feedback', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_feedback_vendor_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('ix_recommendation_feedback_recommendation_id'), table_name='recommendation_feedback')
    op.drop_index('idx_feedback_vendor_submitted', table_name='recommendation_feedback')
    op.drop_index('idx_feedback_rating', table_name='recommendation_feedback')
    op.drop_index('idx_feedback_accuracy', table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    op.drop_index('ix_usage_vendor_type_period', table_name='usage_records')
    op.drop_index('ix_usage_subscription_timestamp', table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_vendor_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_usage_type'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_timestamp'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_subscription_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_recommendations_venue_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_venue_date', table_name='recommendations')
    op.drop_index('ix_recommendations_vendor_market_date', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_vendor_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_vendor_generated', table_name='recommendations')
    op.drop_index('ix_recommendations_product_date', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_market_date'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_invoices_vendor_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_vendor_id'), table_name='invoices')
    op.drop_index('ix_invoices_vendor_date', table_name='invoices')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_stripe_invoice_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_paid'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index('ix_invoices_due_date', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_venues_vendor_id'), table_name='venues')
    op.drop_index('ix_venues_vendor_active', table_name='venues')
    op.drop_index('ix_venues_name', table_name='venues')
    op.drop_index('ix_venues_location_coords', table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_vendors_square_merchant_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_email'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_user_consents_vendor_id'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_consent_type'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_consent_given'), table_name='user_consents')
    op.drop_index('ix_consent_vendor_given', table_name='user_consents')
    op.drop_index('ix_consent_user_type', table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index('ix_subscriptions_vendor_tier', table_name='subscriptions')
    op.drop_index('ix_subscriptions_vendor_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_vendor_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tier'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_period_end', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_square_tokens_vendor_id'), table_name='square_tokens')
    op.drop_index(op.f('ix_square_tokens_merchant_id'), table_name='square_tokens')
    op.drop_table('square_tokens')
    op.drop_index('ix_sales_vendor_square_order', table_name='sales')
    op.drop_index(op.f('ix_sales_vendor_id'), table_name='sales')
    op.drop_index('ix_sales_vendor_date', table_name='sales')
    op.drop_index(op.f('ix_sales_square_payment_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_square_order_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_square_location_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_index('ix_sales_date_range', table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_products_vendor_id'), table_name='products')
    op.drop_index('ix_products_vendor_category', table_name='products')
    op.drop_index('ix_products_vendor_active', table_name='products')
    op.drop_index(op.f('ix_products_square_variation_id'), table_name='products')
    op.drop_index(op.f('ix_products_square_item_id'), table_name='products')
    op.drop_index('ix_products_square_item', table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payment_methods_vendor_id'), table_name='payment_methods')
    op.drop_index('ix_payment_methods_vendor_default', table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_stripe_payment_method_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_stripe_customer_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_legal_holds_vendor_id'), table_name='legal_holds')
    op.drop_index(op.f('ix_legal_holds_is_active'), table_name='legal_holds')
    op.drop_index(op.f('ix_legal_holds_hold_name'), table_name='legal_holds')
    op.drop_index('ix_legal_hold_vendor_active', table_name='legal_holds')
    op.drop_table('legal_holds')
    op.drop_index(op.f('ix_event_data_vendor_id'), table_name='event_data')
    op.drop_index('ix_event_data_vendor_date', table_name='event_data')
    op.drop_index('ix_event_data_location', table_name='event_data')
    op.drop_index(op.f('ix_event_data_eventbrite_id'), table_name='event_data')
    op.drop_index(op.f('ix_event_data_event_date'), table_name='event_data')
    op.drop_index('ix_event_data_date_range', table_name='event_data')
    op.drop_table('event_data')
    op.drop_index('ix_dsar_vendor_status', table_name='data_subject_requests')
    op.drop_index('ix_dsar_user_type', table_name='data_subject_requests')
    op.drop_index('ix_dsar_deadline', table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_vendor_id'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_user_id'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_user_email'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_status'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_requested_at'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_request_type'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_deadline'), table_name='data_subject_requests')
    op.drop_table('data_subject_requests')
    op.drop_index('ix_retention_vendor_type', table_name='data_retention_policies')
    op.drop_index(op.f('ix_data_retention_policies_vendor_id'), table_name='data_retention_policies')
    op.drop_index(op.f('ix_data_retention_policies_is_active'), table_name='data_retention_policies')
    op.drop_index(op.f('ix_data_retention_policies_data_type'), table_name='data_retention_policies')
    op.drop_table('data_retention_policies')
    op.drop_index('ix_deletion_vendor_type_date', table_name='data_deletion_logs')
    op.drop_index('ix_deletion_reason', table_name='data_deletion_logs')
    op.drop_index(op.f('ix_data_deletion_logs_vendor_id'), table_name='data_deletion_logs')
    op.drop_index(op.f('ix_data_deletion_logs_deleted_at'), table_name='data_deletion_logs')
    op.drop_index(op.f('ix_data_deletion_logs_data_type'), table_name='data_deletion_logs')
    op.drop_table('data_deletion_logs')
    op.drop_index('ix_data_access_vendor_type', table_name='data_access_logs')
    op.drop_index('ix_data_access_subject_time', table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_vendor_id'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_data_type'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_data_subject_id'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_correlation_id'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_accessor_id'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_accessed_at'), table_name='data_access_logs')
    op.drop_index('ix_data_access_accessor_time', table_name='data_access_logs')
    op.drop_table('data_access_logs')
    op.drop_index('ix_audit_vendor_action_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_user_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_timestamp_sensitive', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_vendor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_email'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_sensitive'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
